### PR TITLE
Bump base for GHC 9.4

### PR DESCRIPTION
**Pull request by andreasabel**
Also update `tested-with` field to latest GHC versions.

### CODE REVIEW

**Comment by andreasabel** [comment]
Revision pushed to Hackage: https://hackage.haskell.org/package/HaXml-1.25.9/revisions/

**Comment by juhp** [comment]
Okay I updated the action versions, so I hope that makes 9.4 install work.

Thanks for this!

**Comment by juhp** [comment]
(But no - I might temporarily disable the action for 9.4 until this is resolved. :-|)

**Comment by juhp** [comment]
Ah I see you are [on top of this too](haskell/actions#113), great

**Comment by juhp** [comment]
Released in [HaXml-1.25.10](https://hackage.haskell.org/package/HaXml-1.25.10), thank you

**Pull request merged**
