### PR TITLE
HaXml 1.25.12 revsion 1: allow base-4.18; include GHC 9.6.1 alpha in CI

### PR DESCRIPTION
**Pull request by andreasabel**
This is supposed to pushed to Hackage as a revision.

### CODE REVIEW

**Comment by andreasabel** [comment]
@juhp : Not sure why the actions are not started on this PR.

**Comment by andreasabel** [comment]
> @juhp : Not sure why the actions are not started on this PR.

Ah, somehow the `master` branch was renamed to `main`.  This is how you kick your own balls.

**Comment by juhp** [comment]
Or can we just drop the GH action change?  I am fine with merging the base bump.

**Comment by juhp** [comment]
I made a revision on Hackage

**Comment by andreasabel** [comment]
Sure, feel free to close this PR.  

I was kinda curious to see the new `ghcup-release-channel` feature of `haskell/actions/setup` in action.
Btw, do you know why actions are not starting on PRs here?

**Comment by andreasabel** [comment]
Oh, I now see that I got a github notification:

[Invalid workflow file: .github/workflows/build.yml#L16](https://github.com/HaXml/HaXml/actions/runs/3989476758/workflow)
The workflow is not valid. .github/workflows/build.yml (Line: 16, Col: 11): A mapping was not expected

Weird that nothing is reported here on the PR page about it.  So it is a GitHub UI bug.

**Comment by andreasabel** [comment]
Now CI passes, including GHC 9.6.0.20230111.

> Or can we just drop the GH action change? I am fine with merging the base bump.

I opened a new PR to this extent:
- #15 

So, choose your weapon! ;-)

**Comment by juhp** [comment]
Thank you!  I think I prefer to wait for the official 9.6.1 release but thanks for testing it out!

Closing in favour of your #15

**Pull request closed without merging**
