### PR TITLE
P0S is not a valid xml duration, should be PT0S

### PR DESCRIPTION
**Pull request by dten**
relating to this comment, P0S was a mistake, though i also noticed making this edit that the example data contained it

https://github.com/HaXml/HaXml/issues/1#issuecomment-1427936487

### CODE REVIEW

**Comment by dten** [comment]
Super awkward bump just in case this got forgotten 😅😅

**Comment by juhp** [comment]
Sorry this took so long

**Comment by dten** [comment]
Better late than never 🎉 thanks

**Comment by juhp** [comment]
Finally released also as [HaXml-1.25.13](https://hackage.haskell.org/package/HaXml-1.25.13)

**Pull request merged**
